### ISSUE TITLE
在编译OP固件时，配置里看不见ddnsto呢，无法选择，不知道怎么解决呢

### ISSUE THREAD

**Issue by rq1025330** [linkease/nas-packages#1]
在编译OP固件时，配置里看不见ddnsto呢，无法选择，不知道怎么解决呢

**Comment by jjm2473** [comment]
这个步骤执行了吗 https://github.com/linkease/nas-packages#%E5%A2%9E%E5%8A%A0feed%E6%BA%90

**Comment by rq1025330** [comment]
> 这个步骤执行了吗 https://github.com/linkease/nas-packages#%E5%A2%9E%E5%8A%A0feed%E6%BA%90

现在可以了 ，前几天不知道怎么回事

**Comment by jjm2473** [comment]
估计是没feed update或者install
