### ISSUE TITLE
linkease 0.9.2 的一个疑问

### ISSUE THREAD

**Issue by sbwml** [linkease/nas-packages#29]
最新的 linkease 0.9.2 需要依赖 [ffmpeg-remux](https://github.com/linkease/nas-packages/blob/master/multimedia/ffmpeg-remux/Makefile) 包，请问这是最新版本 linkease 工作必须的吗？假如仅安装 linkease，不编译 ffmpeg-remux 包，是否会影响 linkease 的正常工作？

**Comment by jjm2473** [comment]
如果不需要相册生成缩略图的功能，就可以不依赖remux包。或者remux换成完整版的ffmpeg也行

**Comment by sbwml** [comment]
> 如果不需要相册生成缩略图的功能，就可以不依赖remux包。或者remux换成完整版的ffmpeg也行

明白！！
