### ISSUE TITLE
卸载istorex后luci侧边栏依然有首页

### ISSUE THREAD

**Issue by zhaxingyu** [linkease/nas-packages#37]
![image](https://github.com/user-attachments/assets/fcdd4621-54fe-40a2-9f3e-3cae62cf4398)

**Comment by zhaxingyu** [comment]
原来Kwrt自带首页按钮

**Comment by jjm2473** [comment]
首页又不是istorex提供的，而是quickstart提供的。istorex只是依赖了quickstart，卸载istorex时不会卸载quickstart。
