### ISSUE TITLE
ddnsto软件包安装到openwrt21.02之后，无法正常启动

### ISSUE THREAD

**Issue by ziguayungui** [linkease/nas-packages#5]
我通过源码编译并在openwrt21.02 x86_64软路由上并安装了ddnsto package包。
页面配置上选择enable、填入token之后，点击save&apply, 页面依旧提示 The DDNS.to service is not running.
ssh进入设备后台，发现ddns.to进程未启动。

**Comment by Jan20th9e** [comment]
+1

**Comment by jannson** [comment]
luci-compat

估计是的依赖这个包。
